### ISSUE TITLE
Fails when no secrets exist in a path

### ISSUE THREAD

**Issue by obrienrobert** [FalcoSuessgott/vkv#142]
When listing all secrets via it fails when it hits a path with no secrets:

```
./vkv export --path secret/<path>
[ERROR] no secrets in secret/<path> found
```
Maybe there is a way around this other than creating a secret in the failing path?

**Comment by FalcoSuessgott** [comment]
Hi @obrienrobert,

yup, that's a known limitation currently. But it shouldn't be too hard to introduce a flag something like `--ignore-errors`.

I will try to fiix this and come back to you

**Comment by FalcoSuessgott** [comment]
Actually, I can't reproduce this. Which version are you using?

```bash
vault kv list secret      
Keys
----
o  # empty
ok # empty
oko
okokok/
```

```bash
vkv export -p secret  
secret/
├── v1: o
├── v1: ok
├── v1: oko
│   └── okok=****
└── okokok/
    └── v1: okoko
        └── okok=****
```

**Comment by obrienrobert** [comment]
Thanks for getting back to me so quickly. Really helpful tool BTW :) 

```
vault version
Vault v1.13.2 (b9b773f1628260423e6cc9745531fd903cae853f), built 2023-04-25T13:02:50Z

./vkv version
vkv 0.2.2
```

It's working for me now as well. The timeline/steps I took:

- I had an empty secret in a path. Even though the secret was empty, Vault was displaying a message in the UI, something similar or exactly like [this](https://global.discourse-cdn.com/hashicorp/optimized/3X/8/7/87e8dc4efd1c48096ad6fd0cfcd476cbc75a1bb3_2_690x229.png). When I ran vkv it failed
- I populated the secret with dummy values, then vkv worked
- I deleted the dummy secret and then ran vkv, which worked

It looks like it failed when the `Version X of this secret has been deleted` text was displaying in the screen.

**Comment by FalcoSuessgott** [comment]
Very interesting. Thanks for the write-up. Nevertheless a flag like `ignore-errors` is quite helpful especially if your current token policy does not allow reading/listing certain paths in which case `vkv` would fail. So I will try to look into that :)
