### ISSUE TITLE
Top-level paths are lost during import

### ISSUE THREAD

**Issue by crux-capacitor** [FalcoSuessgott/vkv#212]
Hello. This may be user error, but I'm trying to import from a json file that I created using `vkv snapshot save`. I actually have 4 of these files, one for each KV engine that I have.

When importing, the top-level paths are lost. Here's an example of the data:

```json
{
  "toplevel/": {
    "sublevel": {
      "AWS_ACCESS_KEY_ID": "laskdfjalskdjfl",
      "AWS_DEFAULT_REGION": "us-east-1",
      "AWS_SECRET_ACCESS_KEY": "kasdhflksdjfls",
```

My import command looks like this:

```bash
./vkv import -f vault-export-2024-02-15/cicd.yaml -p cicd
```

Then, when I see the secrets in Vault, `toplevel` is gone, and so the path will be like `cicd/sublevel/`.

I think I'm probably doing something wrong. Any help would be appreciated. Thanks.

**Comment by FalcoSuessgott** [comment]
Thanks for the report. I will try to reproduce it and get back to you very soon!

**Comment by FalcoSuessgott** [comment]
Okay, got it:

You have to omit `-p cicd` since that tells `vkv` to import the secrets under the specified mount. I chose that behavior, because this way you can move KV secrets to other mounts or even subpaths :) 

LMK if that solved your problem

**Comment by crux-capacitor** [comment]
@FalcoSuessgott it won't even allow that:

```bash
[root@ip-10-2-162-214 ~]# ./vkv import -f vault-export-2024-02-15/cicd.yaml
[ERROR] no KV-path given, -path / -p needs to be specified.
```

I do want `cicd/` in the path, as that is the name of that KV engine. So the full path should end up being `cicd/toplevel/sublevel`.

Thanks for checking on this.

**Comment by FalcoSuessgott** [comment]
Oh I see, you are using `vkv import`. I was speaking of  `vkv snapshot restore`, which lets you restore a snapshot export at the specified path. In general a `vkv` snapshot works better with `vkv snapshot restore`. Maybe that also works in your case.

However, using `vkv import`, you can simply move secrets around by piping the yaml/json output of `vkv export` into `vkv import`:

```bash
>  vkv export -p secret
secret/
├── v1: admin [key=value]
│   └── sub=********
├── v1: demo
│   └── foo=***
└── sub/
    ├── v1: demo
    │   ├── demo=***********
    │   ├── password=******
    │   └── user=*****
    └── sub2
        └── v2: demo [admin=false key=value]
            ├── admin=***
            ├── foo=***
            ├── password=********
            └── user=****

>  vkv export -p secret -f yaml | vkv import - -p cicd/secret --force
reading secrets from STDIN
parsing secrets from YAML
writing secret "cicd/secret/admin" 
writing secret "cicd/secret/demo" 
writing secret "cicd/secret/sub/sub2/demo" 
writing secret "cicd/secret/sub/demo" 
successfully imported all secrets

result:

cicd/secret/
└── secret/
    ├── admin
    │   └── sub=********
    ├── demo
    │   └── foo=***
    └── sub
        ├── demo
        │   ├── demo=***********
        │   ├── password=******
        │   └── user=*****
        └── sub2
            └── demo
                ├── admin=***
                ├── foo=***
                ├── password=********
                └── user=****

>  vkv export -p cicd   
cicd/
└── secret/
    ├── v2: admin
    │   └── sub=********
    ├── v2: demo
    │   └── foo=***
    └── sub
        ├── v2: demo
        │   ├── demo=***********
        │   ├── password=******
        │   └── user=*****
        └── sub2
            └── v2: demo
                ├── admin=***
                ├── foo=***
                ├── password=********
                └── user=****
```

**Comment by crux-capacitor** [comment]
Aha, yes that did. See, I knew I was doing something wrong 😆 
Thanks for your help.
