### ISSUE TITLE
VKV version 0.7.1 and later suddenly fail with "[ERROR] not authenticated..." Worked on 0.7.0.

### ISSUE THREAD

**Issue by emielkuiper** [FalcoSuessgott/vkv#305]
Hello,

With vkv versions 0.7.1 and later I get an error on some operations like 'vkv list engines' and 'vkv export'.

### Some background
- we tested this setup on an ARM64 Mac using Minikube
- vkv binaries used are therefore also Darwin arm64 binaries
- errors reproduced on Vault versions 1.16.3 AND 1.18.0
- engine tested is Vault KV2 engine
- we use multiple Vault instances in multiple namespaces so naming scheme for engine mount points is "<k8s-namespace>/<name-of-secret-engine>"
- in this case, on Minikube namespace 'default', the KV2 engine 'secrets' is mounted on mountpoint 'default/secrets'

### Mountpoint info Vault
```
vault 2024-10-28T10:49:32.364Z [INFO]  core: successfully mounted: type=system version="v1.18.0+builtin.vault" path=sys/ namespace="ID: root. Path: "
vault 2024-10-28T10:49:32.365Z [INFO]  core: successfully mounted: type=identity version="v1.18.0+builtin.vault" path=identity/ namespace="ID: root. Path: "
vault 2024-10-28T10:49:32.365Z [INFO]  core: successfully mounted: type=cubbyhole version="v1.18.0+builtin.vault" path=cubbyhole/ namespace="ID: root. Path: "
vault 2024-10-28T10:49:32.365Z [INFO]  core: successfully mounted: type=kv version="v0.20.0+builtin" path=default/secrets/ namespace="ID: root. Path: "
vault 2024-10-28T10:49:32.367Z [INFO]  core: successfully mounted: type=token version="v1.18.0+builtin.vault" path=token/ namespace="ID: root. Path: "
vault 2024-10-28T10:49:32.367Z [INFO]  core: successfully mounted: type=userpass version="v1.18.0+builtin.vault" path=default/userpass/ namespace="ID: root. Path: "
vault 2024-10-28T10:49:32.368Z [INFO]  core: successfully mounted: type=approle version="v1.18.0+builtin.vault" path=default/approle/ namespace="ID: root. Path: "
```

### How to reproduce
In this testsetup I have the VAULT_TOKEN env var set, containing the ROOT TOKEN of the targeted Vault instance.

Also I have the following additional env vars set:
```
$ printenv | grep ^VKV
VKV_EXPORT_FORMAT=json
VKV_LIST_ENGINES_FORMAT=json
VKV_EXPORT_ENGINE_PATH=default/secrets

$ printenv | grep ^VAULT
VAULT_FORMAT=json
VAULT_ADDR=https://xxx-vault.xxx.localdev
VAULT_TOKEN=hvs.xxxxxxxxxx
VAULT_SKIP_VERIFY=true
```

The vkv version 0.7.0 outputs the following:
```
$ vkv-0.7.0 version
vkv 0.7.0

$ vkv-0.7.0 list engines
{
  "engines": [
    "default/secrets/"
  ]
}
$ vkv-0.7.0 export 
{
  "default/secrets": {
    "foo/": {
      "bar/": {
        "testkey2": {
          "value": "testvalue2"
        }
      },
      "testkey1": {
        "value": "testvalue1"
      }
    }
(...)
```

The vkv version 0.7.1 and later all output like the following:
```
$ vkv-0.7.1 version
vkv 0.7.1

$ vkv-0.7.1 list engines
[ERROR] not authenticated, perhaps not a valid token: Error making API request.

URL: GET https://xxx-vault.xxx.localdev/v1/auth/token/lookup-self
Code: 403. Errors:

* 2 errors occurred:
        * permission denied
        * invalid token


$ vkv-0.7.1 export 
[ERROR] not authenticated, perhaps not a valid token: Error making API request.

URL: GET https://xxx-vault.xxx.localdev/v1/auth/token/lookup-self
Code: 403. Errors:

* 2 errors occurred:
        * permission denied
        * invalid token

.
```

Could not find any clues in web documentation / 'vkv --help' output.

Hope you can help / advise on this matter.

Best regards,

Emiel Kuiper

**Comment by FalcoSuessgott** [comment]
Thanks for the detailed bug @emielkuiper I will have a look and report back to you!

**Comment by emielkuiper** [comment]
@FalcoSuessgott: it's time for my walk of shame I guess. 

After I submitted this report I went through all of the closed issues one more time.

In one of the posts I saw you refer to the file ~/.vault-token.

I was so hung-up on the correct token being present in env var VAULT_TOKEN that I never
even realised that I indeed had a ~/.vault-token file present in my homedir.

This file was a left-over from a previous (vault cli) test with another Vault installation
which I completely forgot about.

I removed this file and version 0.8.1 apparantly picked up the value in my env var VAULT_TOKEN.

Listing engines / exporting now also works with version 0.8.1.

Was this order-of-precedence (first use ~/.vault-token and only then env var VAULT_TOKEN) introduced 
in version 0.7.1?

**Comment by FalcoSuessgott** [comment]
That was my guess! https://github.com/FalcoSuessgott/vkv/pull/269 Introduces respecting the vault token helper, my guess is that vkv logic differs from the Vault CLI. I will investigate this since this has happened now twice..

**Comment by emielkuiper** [comment]
> That was my guess! #269 Introduces respecting the vault token helper, my guess is that vkv logic differs from the Vault CLI. I will investigate this since this has happened now twice..

Thanks for looking into this, for now I know that this is the order-of-precedence used. 

Is it perhaps an idea to add an explicit error message when both ~/.vault-token and VAULT_TOKEN are available to vkv
and both evaluate to different/conflicting token values?
